version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi  
    ports:
      - "8000:8080"
    environment:
      - API_BASE_URL=http://fastapi:8080   

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://fastapi:8080   
    depends_on:
      - fastapi