# Data Ingestion:
data_ingestion:
  churn_cutoff_date: '2011-03-31'


# Data Cleaning:
data_cleaning:
  imputation_strategy: median
  capping_quantiles: 0.99


# Finalized  Model (XGBoost):
model_trainer:
  best_params:
    colsample_bytree: 0.6
    gamma: 0.3
    learning_rate: 0.01
    max_depth: 10
    min_child_weight: 3
    n_estimators: 100
    subsample: 0.8
