columns:
  - name: invoice
    dtype: object
    nullable: false
  - name: stockcode
    dtype: object
    nullable: false
  - name: description
    dtype: object
    nullable: true
  - name: quantity
    dtype: int64
    nullable: false
  - name: invoicedate
    dtype: datetime64[ns]
    nullable: false
  - name: price
    dtype: float64
    nullable: false
  - name: customerid
    dtype: int64         
    nullable: false
  - name: country
    dtype: object
    nullable: true