columns:
  - name: Invoice
    dtype: object
    nullable: false
  - name: StockCode
    dtype: object
    nullable: false
  - name: Description
    dtype: object
    nullable: true
  - name: Quantity
    dtype: int64
    nullable: false
  - name: InvoiceDate
    dtype: datetime64[ns]
    nullable: false
  - name: Price
    dtype: float64
    nullable: false
  - name: Customer ID
    dtype: int64         
    nullable: false
  - name: Country
    dtype: object
    nullable: true